---
- name: Extract K9s binary
  ansible.builtin.unarchive:
    src: "https://github.com/derailed/k9s/releases/download/v0.27.4/k9s_Linux_amd64.tar.gz"
    remote_src: yes
    dest: /usr/local/bin
    creates: /usr/local/bin/k9s

- name: Ensure /var/lib/rancher/k3s/server/manifests directory
  ansible.builtin.file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory

- name: Ensure k3s mandatory manifests
  ansible.builtin.template:
    src: '../templates/manifests/{{ item }}.yaml'
    dest: '/var/lib/rancher/k3s/server/manifests/{{ item }}.yaml'
  with_items: '{{ manifests }}'
