---
- name: Install prerequisites debian packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
    install_recommends: no
  vars:
    packages:
      - bsdmainutils
      - build-essential
      - cpio
      - curl
      - gcc
      - git
      - gzip
      - libdbus-glib-1-dev
      - libffi-dev
      - libgirepository1.0-dev
      - libssl-dev
      - make
      - python3-dev
      - python3-venv
      - python3-requests
      - shellcheck
      - vim
      - xxd
